version: '3.8'
services:
  pg_db:
    container_name: pg_blanxart
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: blanxart
    volumes:
    - ./PostgresDb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_blanxart
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"